[project]
name = "shionmusicbot"
version = "1.0.0"
description = "Open-source Telegram voice chat music bot for Shion Music bot."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
  { name = "@blazenxt", email = "m11.galaxy.m581@gmail.com" }
]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W"]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
